#!/usr/bin/env python3
"""Build tiny, original static-QA fixtures and a matching case manifest."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def build(fault: str) -> tuple[bytes, bytes, dict[str, object]]:
    base = bytearray(0x240)
    base[0xA0:0xAC] = b"ATLANTIS QA "
    base[0xAC:0xB0] = b"ATQA"
    base[0x80:0x84] = (0x08000100).to_bytes(4, "little")
    base[0x84:0x88] = (0x08000100).to_bytes(4, "little")
    base[0x100:0x108] = bytes([1, 2, 0xFE, 3, 0, 0xA5, 0xA5, 0xA5])
    candidate = bytearray(base)
    candidate[0x100:0x105] = bytes([4, 5, 0xFE, 6, 0])
    allowed_changes = [["0x100", "0x104"]]
    default_width: int | None = 8
    glyph_widths: dict[str, int] = {}
    if fault == "adjacent":
        candidate[0x106] ^= 0xFF
    elif fault == "pointer":
        candidate[0x80:0x84] = (0x02000000).to_bytes(4, "little")
        allowed_changes.append(["0x80", "0x83"])
    elif fault == "unterminated":
        candidate[0x104] = 4
    elif fault == "control":
        candidate[0x102] = 5
    elif fault == "overflow":
        default_width = 16
    elif fault == "unknown-width":
        default_width = None
        glyph_widths = {"4": 8}
    elif fault == "alias":
        # The second pointer intentionally lacks the first pointer's alias group.
        pass
    elif fault != "none":
        raise ValueError(f"unknown fault: {fault}")
    pointers: list[dict[str, object]] = [{
        "id": "target-pointer",
        "offset": "0x80",
        "encoding": "gba32le",
        "target_ranges": [["0x08000100", "0x08000107"]],
        "alignment": 4,
        "alias_group": "shared-target" if fault == "alias" else None,
    }]
    if pointers[0]["alias_group"] is None:
        pointers[0].pop("alias_group")
    if fault == "alias":
        pointers.append({
            "id": "unexpected-alias",
            "offset": "0x84",
            "encoding": "gba32le",
            "target_ranges": [["0x08000100", "0x08000107"]],
            "alignment": 4,
        })
    layout: dict[str, object] = {
        "glyph_widths": glyph_widths,
        "max_width": 24,
        "max_lines": 1,
    }
    if default_width is not None:
        layout["default_width"] = default_width
    manifest: dict[str, object] = {
        "$schema": "../../schemas/gba-runtime-case.schema.json",
        "format_version": 1,
        "case_id": f"original-fixture-{fault}",
        "description": "Original bytes generated by Project Atlantis; no game content",
        "rom": {
            "sha256": hashlib.sha256(base).hexdigest(),
            "size": len(base),
            "game_code_hex": b"ATQA".hex(),
        },
        "static": {
            "change_policy": {
                "allowed_changed_ranges": allowed_changes,
                "require_change": True,
            },
            "regions": [
                {"id": "target", "offset": "0x100", "length": 5, "policy": "changed"},
                {"id": "adjacent", "offset": "0x105", "length": 3, "policy": "unchanged"},
            ],
            "pointers": pointers,
            "records": [{
                "id": "target-record",
                "offset": "0x100",
                "allocated_length": 8,
                "unit_bytes": 1,
                "terminator": 0,
                "allowed_values": [[1, 6]],
                "control_values": ["0xFE"],
                "preserve_controls": True,
                "layout": layout,
            }],
        },
        "provenance": {
            "license": "CC0-1.0",
            "generator": "examples/gba-runtime-validation/build_fixture.py",
            "fault": fault,
        },
    }
    return bytes(base), bytes(candidate), manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", required=True, type=Path)
    parser.add_argument(
        "--fault",
        choices=("none", "adjacent", "pointer", "unterminated", "control", "overflow", "unknown-width", "alias"),
        default="none",
    )
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    paths = [args.out_dir / "base.gba", args.out_dir / "candidate.gba", args.out_dir / "case.json"]
    if not args.force and any(path.exists() for path in paths):
        parser.error("output exists; use a fresh directory or --force")
    base, candidate, manifest = build(args.fault)
    paths[0].write_bytes(base)
    paths[1].write_bytes(candidate)
    paths[2].write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote fixture fault={args.fault} to {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
